### ISSUE TITLE
Groovesquid is damaged and can't open (mac)

### ISSUE THREAD

**Issue by mymedann** [groovesquid/groovesquid#27]
When I try to install the current versión of Groovesquid on my mac, appears the follow message: 

Spanish: "Groovesquid" está dañado y no puede abrirse. Debe expulsar la imagen de disco.
English: "Groovesquid" is damaged and can't open it. The disk image must be ejected.

After try many times, I don't know what I can do to resolve it.

URL: https://groovesquid.com/download.php?file=Groovesquid.dmg
Navigator: Firefox 35.0.1

![captura de pantalla 2015-02-11 a las 12 49 47](https://cloud.githubusercontent.com/assets/448966/6150358/a3c41584-b1ed-11e4-93f6-ed442b6f4cf0.png)

**Comment by gbhrdt** [comment]
Please read the FAQ at http://groovesquid.com where it says:

This problem can occur on Mac OS X if you are not allowing unsigned applications, therefore the message is wrong and misleading.
To fix it go to System Preferences » Security & Privacy » Allow applications downloaded from:
Then select "Anywhere", because else Apple won't let us run unsigned Java Applications.

https://i.stack.imgur.com/PAIZH.jpg
