### ISSUE TITLE
Change User-Agent

### ISSUE THREAD

**Issue by luciocorrea** [groovesquid/groovesquid#54]
Wouldn't be better to replace User-Agent, and use native clients ones instead of Groovesquid? Using Groovesquid UA it would be a lot easy to be blocked. 

What do you think?

**Comment by gbhrdt** [comment]
Groovesquid is already using its own user agent at sites, where we are "allowed" to use, like Musicbrainz API. When downloading from sites like Deezer or SoundCloud, it uses a browser-like user agent, to not be detected.

**Comment by luciocorrea** [comment]
When it searches for music in Deezer, it uses Groovesquid UA. Check this wireshark log: 




GET /search?q=Taylor+Swift+Kendrick+Lamar+Bad+Blood HTTP/1.1
User-Agent: Groovesquid/0.9.2 +http://groovesquid.com
Host: api.deezer.com
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

**Comment by gbhrdt** [comment]
You're totally right, I'm sorry. I probably chose to use Groovesquid UA on all official APIs - and the Deezer API (https://developers.deezer.com/api) is an official one.
We should clearly define when to use Groovesquid's UA and when not. Since we're downloading from Deezer, we should probably not use our UA.
So, only when querying the Musicbrainz API and our own website?

**Comment by luciocorrea** [comment]
I think it's the best way.
